# Copyright (c) 2018-2019, Fares Abdullah, all rights reserved.

version: '3'
services:
    web:
        image: nginx
        ports:
                - "80:80"
        volumes:
                - &APPVOLUME ./app:/app
                - ./log:/var/log/nginx
                - ./default.conf:/etc/nginx/conf.d/default.conf
        links:
                - php
        networks:
            - monumentalnet
    php:
        image: php:7.2-fpm
        volumes:
                - *APPVOLUME
        networks:
            - monumentalnet
    elasticsearch:
        image: docker.elastic.co/elasticsearch/elasticsearch:6.4.2
        container_name: elasticsearch
        environment:
            - cluster.name=docker-cluster
            - bootstrap.memory_lock=true
            - "ES_JAVA_OPTS=-Xms512m -Xmx512m"
        ulimits:
            memlock:
                soft: -1
                hard: -1
        volumes:
            - esdata1:/usr/share/elasticsearch/data
        networks:
            - monumentalnet

volumes:
    esdata1:
        driver: local

networks:
    monumentalnet:

